#!/usr/bin/env php
<?php

require __DIR__ . "/vendor/autoload.php";

/** @var \Psr\Container\ContainerInterface */
$container = require __DIR__ . "/config/container.php";

// run application
(new Marshal\Server\Runtime\RuntimeDetector($container))
    ->detectRuntime()
    ->run();
